# config
logo: /images/logo.png
menu:
  home: ' '
  articles: articles
  author: author

# Content
excerpt_link: Read more

# Miscellaneous
#rss: /atom.xml
google_analytics:

head:
 favicon: "/img/logo_miccall.png"

 keywords: miccall

 backgroundpic : "img/bg.jpg"

intro:
 name: MICCALL
 slogan: "Whatever is worth doing is worth doing well I'll think of you every step of the way"
 HeadButton: MICCALL

Nav:
  Home_name: 主页 # 主页名字
    is_use_categories : true # 是否启用分类
    categories_name: 分类 # 分类名字
    is_use_archives : false # 是否启用归档
    archives_name: 归档 # 归档名字
    icon: # 导航栏上的图标
        github:
            use: true # 是否启用
            link: https://github.com/miccall # 点击地址
        Twitter:
            use: false
            link:
        Facebook:
            use: false
            link:
        Instagram:
            use: false
            link:
    pages:
    # 自定义连接页
    # link 的参数为相对路径，对应 hexo 目录下的 source 件夹内的相应文件夹
        简历:
            link: "/about/"
        团队 :
            link: "/group/"
        图库 :
            link: "/gallery/"
        标签:
            link: "/tag/"
        #自定义标签名
        #   link：“路径”

    MainFirst: # 导航栏下面的主页
        name: Miccall Metro # 大标题名字
        description: Welcome to my Blog   # 第二标签 描述
        pic_url: /img/me.jpg # 图片地址
        goto_ulr: "" # 点击跳转

    Gallery: # 图库页
        title: Mr.metro
        description: Just another fine responsive

